In [2]:
import pandas as pd
from collections import defaultdict

# =============================
# 1. 参数
# =============================
INPUT_FILE = "./3.cGEP_topgene/ALL_cGEP_top_genes_long_wide_by_cGEP1_70.csv"
OUT_FILE = "./3.cGEP_topgene/cGEP1_70_function_CD8_annotation.csv"

# =============================
# 2. CD8 T marker 基因集
# =============================
marker_dict = {
    "Naive/Memory": {
        "CCR7", "IL7R", "LTB", "TCF7", "LEF1"
    },
    "Cytotoxic": {
        "GZMB", "GNLY", "NKG7", "PRF1", "GZMH"
    },
    "Exhausted": {
        "PDCD1", "HAVCR2", "LAG3", "TOX", "CTLA4"
    },
    "Progenitor_exhausted": {
        "TCF7", "LEF1", "TOX"
    },
    "Cycling": {
        "MKI67", "TOP2A", "HMGB2", "UBE2C", "CENPF"
    },
    "IFN_response": {
        "IFIT1", "IFIT3", "ISG15", "MX1", "STAT1"
    },
    "Trm": {
        "ITGAE", "ZNF683", "CXCR6"
    },
    "Stress": {
        "HSPA1A", "HSP90AA1", "DNAJB1"
    }
}

RIBOSOME_PREFIX = ("RPL", "RPS")

# =============================
# 3. 读取 wide cGEP 表
# =============================
df = pd.read_csv(INPUT_FILE)

# =============================
# 4. 注释函数
# =============================
def annotate_cgep(gene_list):
    genes = set(gene_list)

    # ---- 核糖体程序判断
    ribo_genes = [g for g in genes if g.startswith(RIBOSOME_PREFIX)]
    if len(ribo_genes) / len(genes) > 0.6:
        return {
            "Main_function": "Ribosome / housekeeping",
            "CD8T_state": "Housekeeping",
            "Key_markers": ",".join(ribo_genes[:5])
        }

    # ---- marker 命中统计
    hit_counts = {}
    hit_genes = defaultdict(list)

    for state, markers in marker_dict.items():
        hits = genes & markers
        if hits:
            hit_counts[state] = len(hits)
            hit_genes[state] = list(hits)

    if not hit_counts:
        return {
            "Main_function": "Unknown",
            "CD8T_state": "Unknown",
            "Key_markers": ""
        }

    # ---- 选择命中最多的 CD8 状态
    best_state = max(hit_counts, key=hit_counts.get)

    function_map = {
        "Naive/Memory": "Memory differentiation",
        "Cytotoxic": "Cytotoxicity",
        "Exhausted": "T cell exhaustion",
        "Progenitor_exhausted": "Progenitor exhaustion",
        "Cycling": "Cell cycle",
        "IFN_response": "Interferon response",
        "Trm": "Tissue residency",
        "Stress": "Stress response"
    }

    return {
        "Main_function": function_map.get(best_state, best_state),
        "CD8T_state": best_state,
        "Key_markers": ",".join(hit_genes[best_state][:5])
    }

# =============================
# 5. 对每个 cGEP 做注释
# =============================
results = []

for cgep in df.columns:
    genes = (
        df[cgep]
        .dropna()
        .astype(str)
        .tolist()
    )

    anno = annotate_cgep(genes)

    results.append({
        "cGEP": cgep,
        "Main_function": anno["Main_function"],
        "CD8T_state": anno["CD8T_state"],
        "Key_markers": anno["Key_markers"],
        "Top_genes": ",".join(genes[:10])
    })

# =============================
# 6. 输出结果
# =============================
out_df = pd.DataFrame(results)
out_df.to_csv(OUT_FILE, index=False)

print("✅ 注释完成")
print(f"输出文件: {OUT_FILE}")
print(f"共注释 {out_df.shape[0]} 个 cGEP")

✅ 注释完成
输出文件: ./3.cGEP_topgene/cGEP1_70_function_CD8_annotation.csv
共注释 70 个 cGEP

In [4]:
CD8T_state = out_df[out_df["CD8T_state"] != "Unknown"]
Main_function = out_df[out_df["Main_function"] != "Unknown"]

In [5]:
len(CD8T_state)

33

In [11]:
out_df[~out_df["CD8T_state"].isin(["Unknown", "Housekeeping"])]

,cGEP,Main_function,CD8T_state,Key_markers,Top_genes
1,cGEP2,Interferon response,IFN_response,"ISG15,IFIT3,MX1,IFIT1,STAT1","ISG15,MX1,IFI6,IFIT3,IFIT1,RSAD2,OAS1,IFI44L,I..."
5,cGEP6,T cell exhaustion,Exhausted,"HAVCR2,CTLA4,LAG3","GAPDH,KRT86,GZMB,ENTPD1,TNFRSF9,TIGIT,TNFRSF18..."
6,cGEP7,Stress response,Stress,"DNAJB1,HSP90AA1,HSPA1A","RP11-1033A18.1,DNAJB1,HSP90AA1,HSPA1A,RP11-485..."
7,cGEP8,Cytotoxicity,Cytotoxic,"GNLY,GZMB","GNLY,S100A4,TMSB10,TRBV7-6,IFITM2,RPL39,S100A6..."
9,cGEP10,Memory differentiation,Naive/Memory,"LTB,IL7R","KLRB1,SLC4A10,NCR3,AMICA1,CEBPD,IL7R,LTB,S100A..."
11,cGEP12,Cytotoxicity,Cytotoxic,"GZMH,GZMB,NKG7","TotalSeqC0954,LOC100996919,NKG7,GZMH,TotalseqC..."
16,cGEP17,Cytotoxicity,Cytotoxic,GNLY,"RP11-354E11.2,CRISPLD1,NTM,HDC,GNLY,TYROBP,XCL..."
18,cGEP19,T cell exhaustion,Exhausted,CTLA4,"TNFRSF18,FOXP3,TNFRSF4,IL2RA,LINC01943,BATF,CT..."
19,cGEP20,Cytotoxicity,Cytotoxic,"GZMH,NKG7","TotalSeqC0951,CCL5,CCL4,NKG7,CST7,DUSP2,TRBV7-..."
20,cGEP21,Cell cycle,Cycling,"MKI67,UBE2C,HMGB2,TOP2A,CENPF","UBE2C,C15ORF53,RRM2,TOP2A,STMN1,PCLAF,TUBA1B,T..."
21,cGEP22,T cell exhaustion,Exhausted,"HAVCR2,CTLA4,LAG3","HAVCR2,PRF1,AC069363.1,CTLA4,LAG3,VCAM1,CST7,S..."
22,cGEP23,Memory differentiation,Naive/Memory,LTB,"TMSB4XP4,ACTB,S100A4,PFN1,CD52,ACTG1,TMSB4X,SH..."
26,cGEP27,Cytotoxicity,Cytotoxic,"GNLY,GZMB,PRF1,NKG7","AC245427.1,NKG7,FCGR3A,PRF1,GPR56,FGFBP2,KLRF1..."
28,cGEP29,Cytotoxicity,Cytotoxic,NKG7,"RPS15A,GZMK,RARRES3,RPL28,RPS27,RPL7A,RPL23A,A..."
30,cGEP31,Memory differentiation,Naive/Memory,IL7R,"AIM1,IL7R,TXNIP,SMIM3,TSC22D3,ND5,AC007349.2,C..."
32,cGEP33,Stress response,Stress,"DNAJB1,HSPA1A","DUSP1,HSPA1B,DNAJB1,NR4A1,PPP1R15A,GADD45B,JUN..."
34,cGEP35,Cytotoxicity,Cytotoxic,"PRF1,NKG7","LAG3,CD27,GZMK,CMC1,CADM1,HMOX1,IFI6,ISG20,CST..."
39,cGEP40,Cytotoxicity,Cytotoxic,GNLY,"TYROBP,LOC101060038,KLRC1,KRT81,KRT86,GNLY,KIR..."
40,cGEP41,Memory differentiation,Naive/Memory,"TCF7,CCR7,LEF1","SESN3,CTB-133G6.1,SELL,ASCL1,PASK,SPON1,LHFPL6..."
42,cGEP43,Cytotoxicity,Cytotoxic,GZMB,"ASIP,LILRA4,PTGDS,PLD4,IL3RA,IRF8,FLT3,IRF7,DN..."
43,cGEP44,Cytotoxicity,Cytotoxic,NKG7,"RAB5IF,SRGN,CST7,CREM,NKG7,FTH1,RPS26,LITAF,CX..."
45,cGEP46,Memory differentiation,Naive/Memory,IL7R,"LMNA,VIM,MYADM,TAGLN2,S100A10,ADGRE5,S100A11,C..."
48,cGEP49,Tissue residency,Trm,CXCR6,"KLRB1,CTSH,S100A4,IL26,CCR6,S100A6,SPOCK2,LGAL..."
49,cGEP50,Memory differentiation,Naive/Memory,"LTB,IL7R","VIM,CRIP1,GATA3,S100A4,LTB,S100A10,ANXA1,HIST1..."
51,cGEP52,Cytotoxicity,Cytotoxic,GNLY,"AC020916.1,HLA-DRB1,HLA-DRA,HLA-DRB5,PRMT9,CCL..."
55,cGEP56,Cell cycle,Cycling,"UBE2C,HMGB2,TOP2A","AC253572.1,CDC25C,KIF14,HN1,KIF15,MTFR2,KIAA01..."
57,cGEP58,Memory differentiation,Naive/Memory,LTB,"AK4,DNTT,LDHA,ENO1,PKM,IL9R,MIF,PGK1,MYC,ALDOA"
58,cGEP59,Cytotoxicity,Cytotoxic,"GNLY,PRF1,GZMB","GZMB,CD7,GNLY,CRX,SPINK2,KLRD1,CAPG,LGALS1,LRR..."
61,cGEP62,Tissue residency,Trm,ZNF683,"CD7,KLRC2,KRT81,KRT86,KLRC3,LOC101060038,ZNF68..."
67,cGEP68,Cytotoxicity,Cytotoxic,"GNLY,GZMH,GZMB,NKG7","HLA-H,CYTB,ND4,HLA-A,ND4L,ATP6,ATP8,ND2,ND1,NKG7"

In [6]:
df

,cGEP1,cGEP2,cGEP3,cGEP4,cGEP5,cGEP6,cGEP7,cGEP8,cGEP9,cGEP10,...,cGEP61,cGEP62,cGEP63,cGEP64,cGEP65,cGEP66,cGEP67,cGEP68,cGEP69,cGEP70
0,TotalSeqC0953,ISG15,CYTB,RPL13P12,MT-ND4,GAPDH,RP11-1033A18.1,GNLY,HBB,KLRB1,...,COL3A1,CD7,LINC01297,SFTPC,TPSAB1,MTRNR2L8,LINC01531,HLA-H,IGHGP,AFF3
1,RP11-864N7.2,MX1,ATP6,TotalSeqC0952,MT-CO2,KRT86,DNAJB1,S100A4,HBD,SLC4A10,...,POSTN,KLRC2,STON1,SFTPA2,CNRIP1,RPS4Y1,SEMA3B,CYTB,ID4,ZFP41
2,RP11-234A1.1,IFI6,COX3,EEF1A1,MT-CO3,GZMB,HSP90AA1,TMSB10,AHSP,NCR3,...,COL1A1,KRT81,SLC52A3,SFTPA1,GATA2,DDX3Y,PANK1,ND4,LY6K,MT.ND3
3,RP11-425L10.1,IFIT3,ND4L,TotalSeqC0955,MT-ATP6,ENTPD1,HSPA1A,TRBV7-6,SNCA,AMICA1,...,COL1A2,KRT86,FGFR3,SCGB3A2,RP11-354E11.2,H3F3B,GPR37,HLA-A,TUBB,BEND6
4,RPL13P12,IFIT1,COX2,RPL13,MT-CYB,TNFRSF9,RP11-485G4.2,IFITM2,CA1,CEBPD,...,COL6A1,KLRC3,MSMB,KRT8,PRSS57,MALAT1,ADSSL1,ND4L,RPS20,EVI5
5,RPS12,RSAD2,ND1,RPL34,MT-CO1,TIGIT,HSPA1B,RPL39,HBA2,IL7R,...,COL6A3,LOC101060038,SLC2A5,FTH1,PNMT,CCNL1,RP11-176H8.1,ATP6,RPL29,PLEKHG6
6,TotalseqC0251,OAS1,ND5,TPT1,MT-ND2,TNFRSF18,HSPH1,S100A6,ALAS2,LTB,...,CAPN6,ZNF683,PPARGC1A,AL162511.1,HPGDS,NR4A2,EMILIN1,ATP8,RAB13,UBD
7,RPL13,IFI44L,ND2,RPL32,MT-ND1,CD7,HSP90AB1,TRAV8-1,HBA1,S100A4,...,LUM,CD9,AGR2,KRT18,MS4A2,SRSF7,LINC00839,ND2,TM4SF1,MT.ND2
8,RPL32,ISG20,ATP8,RPS12,MT-ND3,LAYN,HSPE1,ATP5E,SLC4A1,DUSP1,...,SGCD,ND4L,VANGL2,LINC01986,CPA3,CLK1,S100A1,ND1,EEF1A1,C2orf88
9,AC024293.1,LY6E,RPS14P3,AC010343.1,MT-ND5,AC092580.4,HSPD1,SH3BGRL3,SELENBP1,CCR6,...,DCN,CTSW,PDLIM3,RPL7,TPSB2,EIF1,ZNF202,NKG7,HES1,BHLHB9
10,EEF1A1,IFITM1,ND3,RPLP1,SLIT1,LOC101929531,HSPA8,SERF2,SLC25A37,LTK,...,COL6A2,XCL1,RP11-115D19.1,RPS4X,RUNDC3A,RBM39,HSPB2,RNR2,C1QB,RNU12
11,RPL34,CMPK2,MT-ND1,AL365357.1,PVRL4,SNX9,DNAJA1,FXYD5,PDZK1IP1,ZBTB16,...,OAF,TXK,MACROD2,NFKBIA,DPP10,JUN,ADIRF,FGFBP2,TPPP3,CTSK
12,AC016739.2,HERC5,GAS5,IL7R,MT-ND4L,ALOX5AP,RP11-153M3.1,MT-ND3,TRIM58,AQP3,...,ANGPT1,KLRD1,ARHGAP6,CXCL2,RASGRP4,UTY,VN1R1,GZMH,RPL35A,C16orf59
13,RPS18,IRF7,MT-CO3,RPS4XP22,MTATP6P1,TPI1,CACYBP,RPL41,HBM,NFKBIA,...,BOC,CAPG,WNT4,RPLP0,KRT1,TTTY15,SMO,COX2,MT-ND1,SLC44A3
14,RPS28,OAS3,MT-CO2,RPS8,MT-RNR1,CXCL13,HSP90AA2P,MYL12A,HBQ1,IL23R,...,ADGRA2,ND1,KLK2,SFTPB,SVOPL,SBDS,FABP3,ND3,RPL8,MT.ND1
15,RPS3A,MX2,ND4,AC016739.1,TMPRSS11F,TNS3,GOT2P2,S100A11,GMPR,IL4I1,...,SEZ6L2,SRGAP3,ZNF350-AS1,MMP7,TK1,SRSF5,ECHDC3,S100A4,HSP90AB1,OSBPL10.AS1
16,RPL18AP3,EPSTI1,HLA-H,RPS6,ANKRD30A,PGAM1,UBB,TMSB4X,HEMGN,TSPAN15,...,LHFPL2,LINC02446,MOGAT2,RPL3,KEL,AC245014.3,PPP1R3C,COX1,RPS8,RALY.AS1
17,RPL39,PLSCR1,MT-ND2,RPL10,MTRNR2L10,PKM,HSPB1,RPS4Y1,KLHL33,RP11-693N9.2,...,EMILIN1,AMICA1,CDK14,RPSA,EFHC2,BTG1,CKMT2-AS1,LGALS1,PSAT1,COL17A1
18,RPL10,STAT1,MT-ND3,RPL11,RFX6,HAVCR2,BAG3,GZMB,KLF1,ME1,...,SPARC,KIR3DL2,CDC42EP5,ACTB,GVQW1,HSPA5,TM4SF4,SH3BGRL3,RPL7,CTA.221G9.12
19,RPL11,MT2A,MT-ATP6,RPS4X,MT-TH,AC002331.1,ZFAND2A,RPL36A,SLC25A39,RORC,...,DLK1,CYTB,ACPP,SPINT2,KIAA0101,DDX24,PCSK4,ACTB,PCP4,RP11.344P13.6
20,RPS14,USP18,LOC100507217,RPS18,MT-RNR2,RBPJ,TIMM8AP1,TMA7,HBG2,LST1,...,IGF2,ND2,PRRG1,B2M,TYMS,HLA-B,PRDM5,PFN1,SNCG,MT.CO3
21,RPS8,IFIT2,MT-CYB,AL590867.2,WARS2-IT1,PDLIM4,HSPA6,HSPA1A,STRADB,CD69,...,RUNX1T1,SPRY2,CCK,LCN2,TPSD1,HIST1H1E,GSTP1,CTSW,RPL12,RP11.102N12.3
22,RPL30,IFI35,MT-ND4,RPS14,PABPC4L,LAG3,GGNBP1,RPS18,EPB42,RORA,...,EGFR,SPINT2,PLS3,MDK,LGALS12,MIDN,RP11-172H24.4,GZMB,PART1,RP11.297B17.3
23,RPS23,EIF2AK2,MT-ND4L,RPS13,KCNN2,CTSD,PPP1R15A,OST4,PLEK2,CTD-3014M21.1,...,TMEM130,HOPX,CADPS2,RPS6,DHRS9,SSBP3,GPX3,CD8A,HSPA6,FCER2
24,RPS6,XAF1,MT-ND5,CCR7,RNF225,ITGAE,UBC,RPS21,BLVRB,IL18RAP,...,NR2F1,IL2,VEGFA,CD9,GLUL,H1FX,PPFIBP2,ITGB2,IGKC,SLC12A8
25,RPS13,IFI44,MT-CO1,FTH1,SCGB1D2,CTLA4,RP11-142L4.2,S100A10,NFIX,IL22,...,DCX,NCR3,IRX4,HLA-DRB1,CXCL2,RPL27A,S100A16,HLA-DRB5,RPS18,TM4SF1
26,RPL19,SAMD9L,ND6,RPS3A,MTRNR2L9,GOLIM4,HSP90AB3P,TRAV10,NFE2,CCL20,...,GAS1,CD69,CLDN11,JUNB,PDE6G,IFRD1,SOD3,COX3,SELENBP1,MT.ATP6
27,RPL37,TNFSF10,MT-RNR2,RPL30,TMSB4XP8,IFITM10,MIRLET7D,HCST,TNS1,IL26,...,PALM,ND4,ORM1,RACK1,EXD3,ITGAM,S100A14,ND5,IGLC7,ASAP3
28,RPL18A,OASL,AC026366.1,RPL3,MT-ATP8,MYO1E,SERPINH1,PFN1,BNIP3L,CTSH,...,COL4A1,LILRP2,ACSS3,ELF3,PHACTR1,TRA2B,GAS1,FCGR3A,RBP1,ATP2A1
29,RPS27,LAMP3,CRISP3,RPL19,MTRNR2L8,CD82,LOC101928304,IFITM1,IGF2BP2,PHACTR2,...,MGP,EPAS1,KLK3,LDHB,EMID1,YPEL5,PKIB,GNLY,RPL31,LA16c.306E5.2